import type { Node, Edge } from "reactflow";
import { iconMap } from "./icons";
import type {
  LibraryCategory,
  LibraryNode,
  EdgeTheme,
  WhiteboardNodeData,
  WhiteboardEdgeData,
  NodeMetaField,
} from "./types";

export const nodeLibrary: LibraryCategory[] = [
  {
    category: "Sheet Metal & Machining",
    description: "CNC, lathe, cutting, press, and welding steps for discrete manufacturing.",
    accent: "#f97316",
    nodes: [
      {
        label: "Raw Material Store",
        icon: "warehouse",
        color: "#64748b",
        badge: "Stores",
        tagline: "Input buffer",
        category: "Sheet Metal & Machining",
        valueType: "non-value-added",
        wip: "50",
        leadTime: "2 days",
      },
      {
        label: "Sheet Metal Cutting",
        icon: "manufacturing",
        color: "#3b82f6",
        badge: "Cutting",
        tagline: "Shear / laser",
        category: "Sheet Metal & Machining",
        valueType: "value-added",
        processTime: "20m",
        cycleTime: "22m",
        setupTime: "10m",
      },
      {
        label: "CNC Machine",
        icon: "manufacturing",
        color: "#f97316",
        badge: "CNC",
        tagline: "Precision milling",
        category: "Sheet Metal & Machining",
        valueType: "value-added",
        processTime: "45m",
        cycleTime: "50m",
        setupTime: "15m",
      },
      {
        label: "Lathe",
        icon: "manufacturing",
        color: "#ef4444",
        badge: "Turning",
        tagline: "Rotational parts",
        category: "Sheet Metal & Machining",
        valueType: "value-added",
        processTime: "30m",
        cycleTime: "35m",
        setupTime: "10m",
      },
      {
        label: "Press / Forming",
        icon: "industry",
        color: "#8b5cf6",
        badge: "Press",
        tagline: "Bend & form",
        category: "Sheet Metal & Machining",
        valueType: "value-added",
        processTime: "15m",
        cycleTime: "18m",
        setupTime: "8m",
      },
      {
        label: "Welding Station",
        icon: "manufacturing",
        color: "#f59e0b",
        badge: "Weld",
        tagline: "Join & finish",
        category: "Sheet Metal & Machining",
        valueType: "value-added",
        processTime: "40m",
        cycleTime: "45m",
        setupTime: "12m",
      },
      {
        label: "Quality Inspection",
        icon: "quality",
        color: "#10b981",
        badge: "QC",
        tagline: "Measure & verify",
        category: "Sheet Metal & Machining",
        valueType: "non-value-added",
        processTime: "15m",
        cycleTime: "20m",
      },
      {
        label: "Finished Goods Store",
        icon: "inventory",
        color: "#0ea5e9",
        badge: "FGS",
        tagline: "Dispatch ready",
        category: "Sheet Metal & Machining",
        valueType: "non-value-added",
        wip: "20",
      },
    ],
  },
  {
    category: "Strategic Planning",
    description:
      "Vision-to-plan cadence aligning demand, capacity, and business goals.",
    accent: "#6366f1",
    nodes: [
      {
        label: "Sales & Ops Planning",
        icon: "planning",
        color: "#6366f1",
        badge: "Planning",
        tagline: "Monthly cadence",
        category: "Strategic Planning",
        valueType: "enabler",
      },
      {
        label: "Master Schedule",
        icon: "planning",
        color: "#0ea5e9",
        badge: "MPS",
        tagline: "Weekly horizon",
        category: "Strategic Planning",
        valueType: "enabler",
      },
      {
        label: "Demand Forecast",
        icon: "performance",
        color: "#14b8a6",
        badge: "Analytics",
        tagline: "Scenario mix",
        category: "Strategic Planning",
        valueType: "enabler",
      },
    ],
  },
  {
    category: "Procurement & Suppliers",
    description:
      "Inbound flow of materials, supplier collaboration, and assurance.",
    accent: "#38bdf8",
    nodes: [
      {
        label: "Supplier Portal",
        icon: "digital",
        color: "#0ea5e9",
        badge: "Digital",
        tagline: "ASN visibility",
        category: "Procurement & Suppliers",
        valueType: "enabler",
      },
      {
        label: "Raw Material Receipt",
        icon: "truck",
        color: "#3b82f6",
        badge: "Inbound",
        tagline: "Dock-to-stock",
        category: "Procurement & Suppliers",
        valueType: "non-value-added",
      },
      {
        label: "Supplier Audit",
        icon: "quality",
        color: "#f97316",
        badge: "QA",
        tagline: "Capability review",
        category: "Procurement & Suppliers",
        valueType: "non-value-added",
      },
    ],
  },
  {
    category: "Production & Transformation",
    description: "Core value creation across fabrication, assembly, and upkeep.",
    accent: "#f59e0b",
    nodes: [
      {
        label: "Fabrication Cell",
        icon: "manufacturing",
        color: "#f97316",
        badge: "Build",
        tagline: "Cycle time",
        category: "Production & Transformation",
        valueType: "value-added",
      },
      {
        label: "Assembly Line",
        icon: "industry",
        color: "#ef4444",
        badge: "Flow",
        tagline: "Takt alignment",
        category: "Production & Transformation",
        valueType: "value-added",
      },
      {
        label: "Maintenance Station",
        icon: "maintenance",
        color: "#22c55e",
        badge: "Uptime",
        tagline: "TPM checks",
        category: "Production & Transformation",
        valueType: "enabler",
      },
    ],
  },
  {
    category: "Quality & Compliance",
    description: "Assurance layers safeguarding specification and regulatory fit.",
    accent: "#a855f7",
    nodes: [
      {
        label: "Quality Gate",
        icon: "quality",
        color: "#a855f7",
        badge: "Release",
        tagline: "Go/No-Go",
        category: "Quality & Compliance",
        valueType: "non-value-added",
      },
      {
        label: "Lab Testing",
        icon: "inspection",
        color: "#10b981",
        badge: "Validation",
        tagline: "Sample checks",
        category: "Quality & Compliance",
        valueType: "non-value-added",
      },
      {
        label: "Compliance Audit",
        icon: "support",
        color: "#ec4899",
        badge: "Audit",
        tagline: "Regulatory",
        category: "Quality & Compliance",
        valueType: "non-value-added",
      },
    ],
  },
  {
    category: "Logistics & Distribution",
    description: "Physical movement, staging, and fulfilment across the network.",
    accent: "#f97316",
    nodes: [
      {
        label: "Warehouse Buffer",
        icon: "warehouse",
        color: "#f97316",
        badge: "Stock",
        tagline: "Days on hand",
        category: "Logistics & Distribution",
        valueType: "non-value-added",
      },
      {
        label: "Staging Zone",
        icon: "inventory",
        color: "#14b8a6",
        badge: "WIP",
        tagline: "Sequenced",
        category: "Logistics & Distribution",
        valueType: "non-value-added",
      },
      {
        label: "Outbound Shipping",
        icon: "shipping",
        color: "#0ea5e9",
        badge: "Delivery",
        tagline: "Customer",
        category: "Logistics & Distribution",
        valueType: "non-value-added",
      },
    ],
  },
  {
    category: "Information Flow",
    description: "Digital signals, system updates, and decision triggers.",
    accent: "#22d3ee",
    nodes: [
      {
        label: "ERP Update",
        icon: "digital",
        color: "#38bdf8",
        badge: "System",
        tagline: "Real-time",
        category: "Information Flow",
        valueType: "enabler",
      },
      {
        label: "Andon Alert",
        icon: "performance",
        color: "#fb7185",
        badge: "Alert",
        tagline: "Issue flag",
        category: "Information Flow",
        valueType: "non-value-added",
      },
      {
        label: "Analytics Hub",
        icon: "performance",
        color: "#818cf8",
        badge: "Insights",
        tagline: "KPI pulse",
        category: "Information Flow",
        valueType: "enabler",
      },
    ],
  },
  {
    category: "Support & People",
    description: "Enablement layers keeping talent, safety, and governance in sync.",
    accent: "#f472b6",
    nodes: [
      {
        label: "Leadership Huddle",
        icon: "support",
        color: "#f472b6",
        badge: "Daily",
        tagline: "Tier meetings",
        category: "Support & People",
        valueType: "non-value-added",
      },
      {
        label: "Training Session",
        icon: "planning",
        color: "#10b981",
        badge: "Skills",
        tagline: "Standard work",
        category: "Support & People",
        valueType: "enabler",
      },
      {
        label: "Safety Walk",
        icon: "quality",
        color: "#facc15",
        badge: "Safety",
        tagline: "Gemba",
        category: "Support & People",
        valueType: "non-value-added",
      },
    ],
  },
];

export const edgeLibrary: EdgeTheme[] = [
  {
    key: "push",
    label: "Push Flow",
    description:
      "Scheduled material movement driven by upstream planning cues.",
    badge: "Physical",
    color: "#38bdf8",
    width: 2.6,
    marker: "arrowClosed",
    icon: "shipping",
    iconGlyph: "🚚",
  },
  {
    key: "pull",
    label: "Pull Signal",
    description:
      "Downstream demand triggers replenishment via kanban loops.",
    badge: "Kanban",
    color: "#facc15",
    dash: "6 4",
    animated: true,
    width: 2.4,
    marker: "arrow",
    icon: "performance",
    iconGlyph: "🔁",
  },
  {
    key: "communication",
    label: "Communication",
    description: "Meetings, huddles, and voice-of-process feedback signals.",
    badge: "Voice",
    color: "#f472b6",
    dash: "2 4",
    width: 2.2,
    marker: "circle",
    markerColor: "#f472b6",
    icon: "support",
    iconGlyph: "💬",
  },
  {
    key: "signal",
    label: "Electronic Signal",
    description: "Automated data updates or system-to-system triggers.",
    badge: "Digital",
    color: "#34d399",
    dash: "1 6",
    animated: true,
    width: 2.2,
    marker: "square",
    markerColor: "#4ade80",
    icon: "digital",
    iconGlyph: "⚡",
  },
];

export const edgeThemeMap = edgeLibrary.reduce<Record<string, EdgeTheme>>(
  (acc, theme) => {
    acc[theme.key] = theme;
    return acc;
  },
  {}
);

export const DEFAULT_EDGE_VARIANT = "push";

export const initialNodes: Node<WhiteboardNodeData>[] = [
  {
    id: "1",
    type: "custom",
    position: { x: 250, y: 150 },
    data: {
      label: "Truck",
      icon: "truck",
      color: "#FFA500",
      category: "Logistics & Distribution",
      valueType: "non-value-added",
    },
  },
  {
    id: "2",
    type: "custom",
    position: { x: 500, y: 150 },
    data: {
      label: "Manufacturing",
      icon: "manufacturing",
      color: "#3498DB",
      category: "Production & Transformation",
      valueType: "value-added",
    },
  },
];

export const initialEdges: Edge<WhiteboardEdgeData>[] = [];

export const SIDEBAR_WIDTH = 360;
export const TAB_BAR_HEIGHT = 56;
export const CANVAS_TOP_OFFSET = TAB_BAR_HEIGHT + 20;

export const nodeMetaFields: NodeMetaField[] = [
  { key: "processTime", label: "Process Time", placeholder: "e.g. 45 sec" },
  { key: "cycleTime", label: "Cycle Time", placeholder: "e.g. 55 sec" },
  { key: "taktTime", label: "Takt Time", placeholder: "e.g. 60 sec" },
  { key: "setupTime", label: "Setup Time", placeholder: "e.g. 12 min" },
  { key: "leadTime", label: "Lead Time", placeholder: "e.g. 2 days" },
  { key: "wip", label: "Current WIP", placeholder: "e.g. 12 units" },
  { key: "capacity", label: "Daily Capacity", placeholder: "Units/day" },
  { key: "oeeAvailability", label: "OEE — Availability %", placeholder: "e.g. 85" },
  { key: "oeePerformance", label: "OEE — Performance %", placeholder: "e.g. 90" },
  { key: "oeeQuality", label: "OEE — Quality %", placeholder: "e.g. 98" },
  { key: "cost", label: "Cost", placeholder: "e.g. $1200" },
  { key: "owner", label: "Owner", placeholder: "Team or role" },
  {
    key: "notes",
    label: "Notes",
    placeholder: "Any contextual detail, bottlenecks, or improvement ideas",
    multiline: true,
  },
];

export { iconMap }; // re-export for convenience
