import { toPng } from "html-to-image";
import jsPDF from "jspdf";
export async function exportToPdf({ canvasElement, scenarioLabel, dashboardCards, bottleneckLabel, }) {
    const imgData = await toPng(canvasElement, {
        backgroundColor: "#0f172a",
        pixelRatio: 1.5,
    });
    const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const W = 297;
    const H = 210;
    const MARGIN = 12;
    const HEADER_H = 18;
    const dateStr = new Date().toLocaleDateString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
    });
    const drawHeader = (subtitle) => {
        pdf.setFillColor(15, 23, 42);
        pdf.rect(0, 0, W, H, "F");
        pdf.setFillColor(22, 32, 55);
        pdf.rect(0, 0, W, HEADER_H, "F");
        pdf.setTextColor(248, 250, 252);
        pdf.setFontSize(11);
        pdf.setFont("helvetica", "bold");
        pdf.text("LeanSync", MARGIN, 11.5);
        pdf.setTextColor(148, 163, 184);
        pdf.setFontSize(8.5);
        pdf.setFont("helvetica", "normal");
        pdf.text(subtitle, MARGIN + 28, 11.5);
        pdf.setTextColor(71, 85, 105);
        pdf.setFontSize(7.5);
        pdf.text(dateStr, W - MARGIN, 11.5, { align: "right" });
    };
    // ── Page 1: Value Stream Map ────────────────────────────────────────────
    drawHeader(`Value Stream Map — ${scenarioLabel}`);
    const imgY = HEADER_H + 2;
    pdf.addImage(imgData, "PNG", MARGIN, imgY, W - MARGIN * 2, H - imgY - MARGIN);
    // ── Page 2: KPI Summary ─────────────────────────────────────────────────
    pdf.addPage();
    drawHeader(`Performance Summary — ${scenarioLabel}`);
    const CARD_W = 52;
    const CARD_H = 38;
    const CARD_GAP = 5;
    const CARDS_PER_ROW = 5;
    const CARDS_Y = HEADER_H + 10;
    dashboardCards.forEach((card, i) => {
        const col = i % CARDS_PER_ROW;
        const row = Math.floor(i / CARDS_PER_ROW);
        const x = MARGIN + col * (CARD_W + CARD_GAP);
        const y = CARDS_Y + row * (CARD_H + CARD_GAP);
        pdf.setFillColor(22, 32, 55);
        pdf.roundedRect(x, y, CARD_W, CARD_H, 2.5, 2.5, "F");
        pdf.setDrawColor(59, 130, 246);
        pdf.setLineWidth(0.25);
        pdf.roundedRect(x, y, CARD_W, CARD_H, 2.5, 2.5, "S");
        pdf.setTextColor(71, 85, 105);
        pdf.setFontSize(6.5);
        pdf.setFont("helvetica", "normal");
        pdf.text(card.title.toUpperCase(), x + 4, y + 8);
        pdf.setTextColor(248, 250, 252);
        pdf.setFontSize(14);
        pdf.setFont("helvetica", "bold");
        pdf.text(String(card.primary), x + 4, y + 19);
        if (card.accent) {
            pdf.setTextColor(56, 189, 248);
            pdf.setFontSize(7);
            pdf.setFont("helvetica", "normal");
            pdf.text(String(card.accent), x + 4, y + 26);
        }
        if (card.footer) {
            pdf.setTextColor(51, 65, 85);
            pdf.setFontSize(6.5);
            pdf.text(String(card.footer), x + 4, y + 33);
        }
    });
    // Bottleneck alert
    if (bottleneckLabel) {
        const rows = Math.ceil(dashboardCards.length / CARDS_PER_ROW);
        const alertY = CARDS_Y + rows * (CARD_H + CARD_GAP) + 6;
        pdf.setFillColor(69, 10, 10);
        pdf.roundedRect(MARGIN, alertY, W - MARGIN * 2, 18, 2.5, 2.5, "F");
        pdf.setDrawColor(239, 68, 68);
        pdf.setLineWidth(0.3);
        pdf.roundedRect(MARGIN, alertY, W - MARGIN * 2, 18, 2.5, 2.5, "S");
        pdf.setTextColor(252, 165, 165);
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "bold");
        pdf.text(`Bottleneck: ${bottleneckLabel}`, MARGIN + 6, alertY + 7);
        pdf.setTextColor(248, 113, 113);
        pdf.setFontSize(7.5);
        pdf.setFont("helvetica", "normal");
        pdf.text("This step has the highest cycle time — prioritise improvement here first.", MARGIN + 6, alertY + 14);
    }
    // Page footer
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.text("Generated by LeanSync · leansync-demo.web.app", W / 2, H - 5, {
        align: "center",
    });
    pdf.save(`LeanSync-${scenarioLabel.replace(/\s+/g, "-")}-${dateStr.replace(/\s+/g, "-")}.pdf`);
}
